server:
  port : 9001
  
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://122.248.228.175:8761/eureka/
    lease:
      duration: 5
      
spring:
 application:
  name: LISTING-SERVICE		#current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
  
profiles: container
jpa:
    database: MYSQL
    hibernate:
        ddl-auto: validate


datasource:
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver